spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari: #数据库连接池
      pool-name: DateHikariCP #连接池名称
      minimum-idle: 5 #最小空闲连接
      idle-timeout: 1800000 #空闲连接存活最大时间 默认600000（10分钟）
      maximum-pool-size: 10 #最大连接数 默认为10
      auto-commit: true #从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间 0表示永久存活 默认1800000（30分钟）
      connection-timeout: 30000 #连接超时时间 默认30000（30秒）c
      connection-test-query: SELECT 1 #测试连接是否可用的查询语句 心跳连接

  redis:
    host: 192.168.77.136
    port: 6379
    database: 0
    timeout: 10000ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-wait: -1 #最大连接阻塞等待时间 默认-1 一直等待
        max-idle: 8 #最大空闲连接 默认为8
        min-idle: 0 #最小空闲连接 默认为0


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml #配置Mapper.xml映射文件
  type-aliases-package: com.zh.seckill.pojo #配置MyBatis数据返回类型别名（默认别名是类名）

logging: #MyBatis SQL打印（方法接口所在的包，不是Mapper.xml所在包）
  level:
    com.zh.seckill.mapper: debug

